import type { Locale } from './index';
const it = {
  title: 'Campionato', photo: 'Fotografia', music: 'Musica', eyebrow: 'UNSEEN · ELIMINAZIONE DIRETTA',
  intro: '16 partecipanti. 15 duelli. 30 giorni. Il pubblico sceglie chi passa.',
  rounds: ['Ottavi', 'Quarti', 'Semifinali', 'Finale'], champion: 'Campione', bracket: 'Tabellone',
  empty: 'Il prossimo campionato sta prendendo forma.', emptyText: 'I 16 partecipanti saranno pubblicati qui appena il campionato viene programmato. Torna a trovarci o candida la tua opera.',
  submit: 'Candida la tua opera', loading: 'Caricamento campionato…', error: 'Non riesco a caricare il campionato.', retry: 'Riprova',
  scheduled: 'In programma', running: 'In corso', completed: 'Concluso', cancelled: 'Annullato', starts: 'Inizio', ends: 'Finale entro',
  tieRule: 'In parità, anche con zero voti, passa la posizione iniziale più alta: #1 precede #2, e così via.',
  duration: 'Ogni duello dura 48 ore. Si gioca una sfida alla volta, senza pause tra i turni.',
  waiting: 'Vincitore duello', votes: 'voti', vote: 'Vota questa opera', voted: 'Voto registrato', login: 'Accedi per votare',
  view: 'Apri duello', live: 'In gara', remaining: 'Tempo rimanente', noMatch: 'Nessun duello in corso',
  seed: 'Posizione iniziale', lost: 'Eliminato', qualified: 'Qualificato', tie: 'Parità: passa per posizione iniziale',
  share: 'Condividi duello', copied: 'Link copiato', voteError: 'Voto non registrato',
  history: 'Campionati precedenti', progress: 'duelli conclusi', scroll: 'Scorri il tabellone per seguire tutti i turni →',
  match: 'duello', matches: 'duelli', participants: 'partecipanti', slot: 'Posizione',
  secretVotes: 'Voti segreti fino alla fine del duello',
};
type Copy = typeof it;
const en: Copy = { ...it, secretVotes: "Votes hidden until the match ends", match: 'match', matches: 'matches', participants: 'participants', slot: 'Slot', title: 'Championship', photo: 'Photography', music: 'Music', eyebrow: 'UNSEEN · SINGLE ELIMINATION', intro: '16 participants. 15 matches. 30 days. The public decides who advances.', rounds: ['Round of 16', 'Quarterfinals', 'Semifinals', 'Final'], champion: 'Champion', bracket: 'Bracket', empty: 'The next championship is taking shape.', emptyText: 'The 16 participants will appear here once the championship is scheduled. Come back soon or submit your work.', submit: 'Submit your work', loading: 'Loading championship…', error: 'Unable to load the championship.', retry: 'Retry', scheduled: 'Scheduled', running: 'Live', completed: 'Completed', cancelled: 'Cancelled', starts: 'Starts', ends: 'Final ends', tieRule: 'Ties, including zero votes, are decided by initial seed: #1 takes priority over #2, and so on.', duration: 'Each match lasts 48 hours. One match at a time, with no gaps between rounds.', waiting: 'Winner of match', votes: 'votes', vote: 'Vote for this work', voted: 'Vote recorded', login: 'Log in to vote', view: 'Open match', live: 'Live', remaining: 'Time remaining', noMatch: 'No match in progress', seed: 'Initial seed', lost: 'Eliminated', qualified: 'Qualified', tie: 'Tie: advances by initial seed', share: 'Share match', copied: 'Link copied', voteError: 'Vote not recorded', history: 'Previous championships', progress: 'matches completed', scroll: 'Scroll the bracket to follow every round →' };
const es: Copy = { ...en, secretVotes: "Votos secretos hasta el final del duelo", match: 'duelo', matches: 'duelos', participants: 'participantes', slot: 'Posici?n', title: 'Campeonato', photo: 'Fotografía', music: 'Música', intro: '16 participantes. 15 duelos. 30 días. El público decide quién avanza.', rounds: ['Octavos', 'Cuartos', 'Semifinales', 'Final'], champion: 'Campeón', bracket: 'Cuadro', vote: 'Votar esta obra', voted: 'Voto registrado', login: 'Accede para votar', empty: 'El próximo campeonato está tomando forma.', tieRule: 'En empate, incluso con cero votos, avanza la mejor posición inicial: #1 antes de #2.', duration: 'Cada duelo dura 48 horas. Se juega uno a la vez, sin pausas.', scheduled: 'Programado', running: 'En curso', completed: 'Finalizado', cancelled: 'Cancelado', starts: 'Inicio', ends: 'Fin de la final', lost: 'Eliminado', qualified: 'Clasificado', live: 'En juego', view: 'Abrir duelo', remaining: 'Tiempo restante', waiting: 'Ganador del duelo', votes: 'votos', seed: 'Posición inicial' };
const fr: Copy = { ...en, secretVotes: "Votes cach?s jusqu?? la fin du duel", match: 'duel', matches: 'duels', participants: 'participants', slot: 'Position', title: 'Championnat', photo: 'Photographie', music: 'Musique', intro: '16 participants. 15 duels. 30 jours. Le public décide qui avance.', rounds: ['Huitièmes', 'Quarts', 'Demi-finales', 'Finale'], champion: 'Champion', bracket: 'Tableau', vote: 'Voter pour cette œuvre', voted: 'Vote enregistré', login: 'Connectez-vous pour voter', empty: 'Le prochain championnat se prépare.', tieRule: 'En cas d’égalité, même sans votes, la meilleure position initiale avance : #1 avant #2.', duration: 'Chaque duel dure 48 heures. Un seul duel à la fois, sans pause.', scheduled: 'Programmé', running: 'En cours', completed: 'Terminé', cancelled: 'Annulé', starts: 'Début', ends: 'Fin de la finale', lost: 'Éliminé', qualified: 'Qualifié', live: 'En lice', view: 'Ouvrir le duel', remaining: 'Temps restant', waiting: 'Vainqueur du duel', votes: 'votes', seed: 'Position initiale' };
const de: Copy = { ...en, secretVotes: "Stimmen bis zum Duellende verborgen", match: 'Duell', matches: 'Duelle', participants: 'Teilnehmer', slot: 'Position', title: 'Meisterschaft', photo: 'Fotografie', music: 'Musik', intro: '16 Teilnehmer. 15 Duelle. 30 Tage. Das Publikum entscheidet, wer weiterkommt.', rounds: ['Achtelfinale', 'Viertelfinale', 'Halbfinale', 'Finale'], champion: 'Sieger', bracket: 'Turnierbaum', vote: 'Für dieses Werk stimmen', voted: 'Stimme gespeichert', login: 'Zum Abstimmen anmelden', empty: 'Die nächste Meisterschaft wird vorbereitet.', tieRule: 'Bei Gleichstand, auch ohne Stimmen, gewinnt die bessere Startposition: #1 vor #2.', duration: 'Jedes Duell dauert 48 Stunden. Ein Duell nach dem anderen, ohne Pause.', scheduled: 'Geplant', running: 'Läuft', completed: 'Beendet', cancelled: 'Abgebrochen', starts: 'Start', ends: 'Finalende', lost: 'Ausgeschieden', qualified: 'Weiter', live: 'Im Duell', view: 'Duell öffnen', remaining: 'Verbleibende Zeit', waiting: 'Sieger von Duell', votes: 'Stimmen', seed: 'Startposition' };
export const championshipCopy: Record<Locale, Copy> = { it, en, es, fr, de };
