import type { Locale } from './index';

const it = {
  badge: 'CANDIDATURE MUSICALI', heading: 'Fai sentire il tuo suono.', intro: 'Scegli il momento che ti rappresenta. Noi gli diamo un palco.',
  stepFiles: 'Il tuo sound', stepDetails: 'La tua identità', stepLinks: 'Il brano, altrove', optional: 'Facoltativo',
  filesHint: 'Una copertina e il tuo audio. Poi scegli l’estratto da portare nell’arena.',
  pickCover: 'Scegli copertina', pickAudio: 'Scegli audio', change: 'Sostituisci',
  previewHint: 'La tua copertina diventa un vinile. Carica i file per vedere e ascoltare l’anteprima.', previewBadge: 'COME TI VEDRÀ IL PUBBLICO',
  clip: 'Scegli il tuo momento', clipHint: 'Muovi i cursori o inserisci i secondi esatti. Verrà caricato solo l’estratto selezionato, fino a 40 secondi.',
  start: 'Inizio (secondi)', end: 'Fine (secondi)', startSlider: 'Sposta l’inizio dell’estratto', endSlider: 'Sposta la fine dell’estratto',
  selected: 'Estratto selezionato', original: 'Audio originale', previewClip: 'Ascolta estratto', pauseClip: 'Ferma anteprima',
  decoding: 'Analisi del tuo audio…', preparing: 'Preparazione estratto…', audioFailure: 'Non riesco a leggere questo audio. Prova un altro file MP3 o WAV.',
  instagram: 'Username Instagram', instagramHint: 'Il tuo @nome sarà cliccabile e porterà direttamente al tuo profilo.',
  linksHint: 'Hai già pubblicato questo brano? Aggiungi i suoi link ufficiali.', youtube: 'Video YouTube', reel: 'Reel Instagram', spotify: 'Brano su Spotify',
  invalidInstagram: 'Inserisci un username Instagram valido o il link al tuo profilo.', invalidLink: 'Controlla i link: servono un video YouTube, un Reel Instagram e un brano Spotify validi, con https.',
  ready: 'Pronto per la revisione', summary: 'Copertina, estratto e profilo: tutto quello che serve per presentarti.',
  privacy: 'Prima della pubblicazione, audio e copertina sono visibili solo a te e al team.', maxClip: 'FINO A 40 SECONDI', uploadError: 'Invio non riuscito. Riprova tra poco.',
};
type Copy = typeof it;
const en: Copy = {
  badge: 'MUSIC SUBMISSIONS', heading: 'Let your sound be heard.', intro: 'Choose the moment that represents you. We’ll give it a stage.',
  stepFiles: 'Your sound', stepDetails: 'Your identity', stepLinks: 'Your track, elsewhere', optional: 'Optional',
  filesHint: 'A cover and your audio. Then choose the excerpt for the arena.', pickCover: 'Choose cover', pickAudio: 'Choose audio', change: 'Replace',
  previewHint: 'Your cover becomes a record. Upload your files to see and hear the preview.', previewBadge: 'HOW THE PUBLIC WILL SEE YOU',
  clip: 'Choose your moment', clipHint: 'Move the sliders or enter exact seconds. Only the selected excerpt will be uploaded, up to 40 seconds.',
  start: 'Start (seconds)', end: 'End (seconds)', startSlider: 'Move excerpt start', endSlider: 'Move excerpt end', selected: 'Selected excerpt', original: 'Original audio', previewClip: 'Play excerpt', pauseClip: 'Stop preview',
  decoding: 'Analysing your audio…', preparing: 'Preparing excerpt…', audioFailure: 'Unable to read this audio. Try another MP3 or WAV file.',
  instagram: 'Instagram username', instagramHint: 'Your @name will link directly to your profile.', linksHint: 'Already published this track? Add its official links.', youtube: 'YouTube video', reel: 'Instagram Reel', spotify: 'Spotify track',
  invalidInstagram: 'Enter a valid Instagram username or profile link.', invalidLink: 'Check your links: use a valid YouTube video, Instagram Reel or Spotify track with https.',
  ready: 'Ready for review', summary: 'Cover, excerpt and profile: everything you need to introduce yourself.', privacy: 'Before publication, your audio and cover are visible only to you and the team.', maxClip: 'UP TO 40 SECONDS', uploadError: 'Submission failed. Please try again shortly.',
};
export const musicSubmitCopy: Record<Locale, Copy> = {
  it, en,
  es: { ...en, badge: 'CANDIDATURAS MUSICALES', heading: 'Haz que se escuche tu sonido.', intro: 'Elige el momento que te representa. Nosotros le damos un escenario.', stepFiles: 'Tu sonido', stepDetails: 'Tu identidad', stepLinks: 'Tu canción, en otros lugares', optional: 'Opcional', filesHint: 'Tu portada y audio. Después elige el fragmento para la arena.', pickCover: 'Elegir portada', pickAudio: 'Elegir audio', change: 'Cambiar', previewHint: 'Tu portada se convierte en un disco. Sube tus archivos para ver y escuchar la vista previa.', previewBadge: 'ASÍ TE VERÁ EL PÚBLICO', clip: 'Elige tu momento', clipHint: 'Mueve los controles o introduce los segundos exactos. Solo se subirá el fragmento elegido, hasta 40 segundos.', start: 'Inicio (segundos)', end: 'Final (segundos)', startSlider: 'Mover inicio del fragmento', endSlider: 'Mover final del fragmento', selected: 'Fragmento elegido', original: 'Audio original', previewClip: 'Escuchar fragmento', pauseClip: 'Parar vista previa', decoding: 'Analizando tu audio…', preparing: 'Preparando fragmento…', audioFailure: 'No se puede leer este audio. Prueba otro MP3 o WAV.', instagram: 'Usuario de Instagram', instagramHint: 'Tu @nombre enlazará directamente a tu perfil.', linksHint: '¿Ya has publicado esta canción? Añade sus enlaces oficiales.', youtube: 'Vídeo de YouTube', reel: 'Reel de Instagram', spotify: 'Canción en Spotify', invalidInstagram: 'Introduce un usuario o perfil de Instagram válido.', invalidLink: 'Usa enlaces https válidos a un vídeo YouTube, Reel Instagram o canción Spotify.', ready: 'Listo para revisión', summary: 'Portada, fragmento y perfil: todo para presentarte.', privacy: 'Antes de publicarse, solo tú y el equipo podéis ver tu audio y portada.', maxClip: 'HASTA 40 SEGUNDOS', uploadError: 'No se pudo enviar. Inténtalo de nuevo.' },
  fr: { ...en, badge: 'CANDIDATURES MUSICALES', heading: 'Fais entendre ton son.', intro: 'Choisis le moment qui te représente. Nous lui donnons une scène.', stepFiles: 'Ton son', stepDetails: 'Ton identité', stepLinks: 'Ton morceau, ailleurs', optional: 'Facultatif', filesHint: 'Ta pochette et ton audio. Puis choisis l’extrait pour l’arène.', pickCover: 'Choisir la pochette', pickAudio: 'Choisir l’audio', change: 'Remplacer', previewHint: 'Ta pochette devient un disque. Ajoute tes fichiers pour voir et écouter l’aperçu.', previewBadge: 'CE QUE LE PUBLIC VERRA', clip: 'Choisis ton moment', clipHint: 'Déplace les curseurs ou saisis les secondes exactes. Seul l’extrait choisi sera envoyé, jusqu’à 40 secondes.', start: 'Début (secondes)', end: 'Fin (secondes)', startSlider: 'Déplacer le début de l’extrait', endSlider: 'Déplacer la fin de l’extrait', selected: 'Extrait sélectionné', original: 'Audio original', previewClip: 'Écouter l’extrait', pauseClip: 'Arrêter l’aperçu', decoding: 'Analyse de ton audio…', preparing: 'Préparation de l’extrait…', audioFailure: 'Impossible de lire cet audio. Essaie un autre MP3 ou WAV.', instagram: 'Pseudo Instagram', instagramHint: 'Ton @nom sera un lien direct vers ton profil.', linksHint: 'Ce morceau est déjà publié ? Ajoute ses liens officiels.', youtube: 'Vidéo YouTube', reel: 'Reel Instagram', spotify: 'Morceau sur Spotify', invalidInstagram: 'Saisis un pseudo ou un profil Instagram valide.', invalidLink: 'Utilise des liens https valides vers une vidéo YouTube, un Reel Instagram ou un morceau Spotify.', ready: 'Prêt pour validation', summary: 'Pochette, extrait et profil : tout pour te présenter.', privacy: 'Avant publication, seuls toi et l’équipe pouvez voir ton audio et ta pochette.', maxClip: 'JUSQU’À 40 SECONDES', uploadError: 'Envoi échoué. Réessaie dans un instant.' },
  de: { ...en, badge: 'MUSIKEINREICHUNGEN', heading: 'Lass deinen Sound hören.', intro: 'Wähle den Moment, der dich repräsentiert. Wir geben ihm eine Bühne.', stepFiles: 'Dein Sound', stepDetails: 'Deine Identität', stepLinks: 'Dein Track, anderswo', optional: 'Optional', filesHint: 'Dein Cover und Audio. Wähle dann den Ausschnitt für die Arena.', pickCover: 'Cover wählen', pickAudio: 'Audio wählen', change: 'Ersetzen', previewHint: 'Dein Cover wird zur Platte. Lade Dateien hoch, um die Vorschau zu sehen und zu hören.', previewBadge: 'SO SIEHT DICH DAS PUBLIKUM', clip: 'Wähle deinen Moment', clipHint: 'Bewege die Regler oder gib genaue Sekunden ein. Nur der gewählte Ausschnitt wird hochgeladen, bis zu 40 Sekunden.', start: 'Beginn (Sekunden)', end: 'Ende (Sekunden)', startSlider: 'Anfang verschieben', endSlider: 'Ende verschieben', selected: 'Gewählter Ausschnitt', original: 'Originalaudio', previewClip: 'Ausschnitt anhören', pauseClip: 'Vorschau stoppen', decoding: 'Audio wird analysiert…', preparing: 'Ausschnitt wird vorbereitet…', audioFailure: 'Audio konnte nicht gelesen werden. Versuche eine andere MP3- oder WAV-Datei.', instagram: 'Instagram-Benutzername', instagramHint: 'Dein @Name verlinkt direkt zu deinem Profil.', linksHint: 'Track bereits veröffentlicht? Füge die offiziellen Links hinzu.', youtube: 'YouTube-Video', reel: 'Instagram-Reel', spotify: 'Track auf Spotify', invalidInstagram: 'Gib einen gültigen Instagram-Namen oder Profillink ein.', invalidLink: 'Verwende gültige https-Links zu einem YouTube-Video, Instagram-Reel oder Spotify-Track.', ready: 'Bereit zur Prüfung', summary: 'Cover, Ausschnitt und Profil: alles für deine Vorstellung.', privacy: 'Vor Veröffentlichung sehen nur du und das Team dein Audio und Cover.', maxClip: 'BIS ZU 40 SEKUNDEN', uploadError: 'Einreichen fehlgeschlagen. Versuche es erneut.' },
};
