import type { Locale } from "./index";

const it = {
  choose: "Scegli la tua arena", chooseIntro: "Due modi di lasciare il segno. Da quale vuoi cominciare?",
  photography: "Fotografica", music: "Musicale", photoDescription: "Due fotografie. Due punti di vista. Scegli l’immagine che ti resta dentro.",
  musicDescription: "Due artisti. Due dischi. Premi play e lascia che sia la musica a parlare.", enter: "Entra nell’arena", new: "Novità",
  back: "Cambia arena", competition: "UNSEEN · COMPETIZIONE MUSICALE", tagline: "Due brani. Una scelta. Il pubblico decide.",
  demo: "Duello di esempio", demoNote: "Artisti immaginari e loop originali di esempio. I voti demo non vengono salvati.",
  play: "Ascolta", pause: "Pausa", seek: "Posizione nel brano", challenger: "Sfidante", listen: "Clicca il disco per ascoltare", playing: "In ascolto",
  share: "Condividi duello", copied: "Link copiato", shareError: "Non è stato possibile condividere il duello.", audioError: "Audio non disponibile. Riprova.",
  vote: "Vota questo brano", voted: "Voto registrato", demoVoted: "Preferenza demo selezionata", voteError: "Non è stato possibile registrare il voto.",
  submit: "Invia il tuo brano", submitIntro: "Il tuo suono, la tua copertina. Il tuo spazio nell’arena.", cover: "Copertina del brano", coverHint: "JPG, PNG o WEBP · massimo 5 MB", audio: "File audio", audioHint: "MP3 o WAV · massimo 30 MB",
  title: "Titolo del brano", artist: "Nome d’arte", story: "La storia del brano", send: "Invia il brano", sending: "Invio in corso…",
  preview: "La tua anteprima", previewHint: "La copertina farà da sfondo al disco. Carica anche l’audio per provarlo.", chooseFiles: "Carica copertina e audio per continuare.",
  invalidCover: "Scegli una copertina JPG, PNG o WEBP, fino a 5 MB.", invalidAudio: "Scegli un file MP3 o WAV, fino a 30 MB.",
  login: "Accedi per inviare il tuo brano.", unavailable: "L’anteprima è pronta. L’invio sarà disponibile quando il servizio musicale sarà collegato.",
  received: "Brano ricevuto", receivedDescription: "Il tuo brano e la copertina sono in attesa di revisione.", another: "Invia un altro brano", review: "Il brano sarà verificato prima di entrare nell’arena.",
  rights: "Confermo di avere i diritti per condividere il brano e la copertina.", photoSubmit: "Invia una fotografia", timeLeft: "Tempo rimasto", ended: "Duello concluso", loading: "Caricamento duello…",
};

export const musicCopy: Record<Locale, typeof it> = {
  it,
  en: {
    choose: "Choose your arena", chooseIntro: "Two ways to leave a mark. Where will you start?", photography: "Photography", music: "Music",
    photoDescription: "Two photographs. Two perspectives. Choose the image that stays with you.", musicDescription: "Two artists. Two records. Press play and let the music speak.", enter: "Enter the arena", new: "New",
    back: "Switch arena", competition: "UNSEEN · MUSIC COMPETITION", tagline: "Two tracks. One choice. The audience decides.", demo: "Sample duel", demoNote: "Fictional artists and original sample loops. Demo votes are not saved.",
    play: "Play", pause: "Pause", seek: "Track position", challenger: "Challenger", listen: "Click the record to listen", playing: "Now playing", share: "Share duel", copied: "Link copied", shareError: "Could not share this duel.", audioError: "Audio unavailable. Please try again.",
    vote: "Vote for this track", voted: "Vote recorded", demoVoted: "Demo preference selected", voteError: "Could not record your vote.", submit: "Submit your track", submitIntro: "Your sound, your cover. Your place in the arena.",
    cover: "Track cover", coverHint: "JPG, PNG or WEBP · up to 5 MB", audio: "Audio file", audioHint: "MP3 or WAV · up to 30 MB", title: "Track title", artist: "Artist name", story: "The story behind the track", send: "Submit track", sending: "Submitting…", preview: "Your preview", previewHint: "Your cover sits behind the record. Add audio to try it out.", chooseFiles: "Add a cover and audio to continue.", invalidCover: "Choose a JPG, PNG or WEBP cover, up to 5 MB.", invalidAudio: "Choose an MP3 or WAV file, up to 30 MB.", login: "Sign in to submit your track.", unavailable: "Your preview is ready. Submissions will open when the music service is connected.", received: "Track received", receivedDescription: "Your track and cover are awaiting review.", another: "Submit another track", review: "Your track will be reviewed before entering the arena.", rights: "I have the rights to share this track and cover.", photoSubmit: "Submit a photograph", timeLeft: "Time remaining", ended: "Duel ended", loading: "Loading duel…",
  },
  es: {
    choose: "Elige tu arena", chooseIntro: "Dos formas de dejar huella. ¿Por dónde empezarás?", photography: "Fotográfica", music: "Musical", photoDescription: "Dos fotografías. Dos perspectivas. Elige la imagen que se queda contigo.", musicDescription: "Dos artistas. Dos discos. Pulsa play y deja hablar a la música.", enter: "Entrar en la arena", new: "Nuevo", back: "Cambiar arena", competition: "UNSEEN · COMPETICIÓN MUSICAL", tagline: "Dos canciones. Una elección. El público decide.", demo: "Duelo de ejemplo", demoNote: "Artistas ficticios y loops originales de ejemplo. Los votos demo no se guardan.", play: "Escuchar", pause: "Pausa", seek: "Posición de la canción", challenger: "Participante", listen: "Pulsa el disco para escuchar", playing: "Reproduciendo", share: "Compartir duelo", copied: "Enlace copiado", shareError: "No se pudo compartir el duelo.", audioError: "Audio no disponible. Inténtalo de nuevo.", vote: "Votar esta canción", voted: "Voto registrado", demoVoted: "Preferencia demo seleccionada", voteError: "No se pudo registrar el voto.", submit: "Envía tu canción", submitIntro: "Tu sonido, tu portada. Tu espacio en la arena.", cover: "Portada de la canción", coverHint: "JPG, PNG o WEBP · máximo 5 MB", audio: "Archivo de audio", audioHint: "MP3 o WAV · máximo 30 MB", title: "Título de la canción", artist: "Nombre artístico", story: "La historia de la canción", send: "Enviar canción", sending: "Enviando…", preview: "Tu vista previa", previewHint: "La portada será el fondo del disco. Añade audio para probarlo.", chooseFiles: "Añade portada y audio para continuar.", invalidCover: "Elige una portada JPG, PNG o WEBP de hasta 5 MB.", invalidAudio: "Elige un archivo MP3 o WAV de hasta 30 MB.", login: "Inicia sesión para enviar tu canción.", unavailable: "Tu vista previa está lista. Los envíos se abrirán cuando el servicio musical esté conectado.", received: "Canción recibida", receivedDescription: "Tu canción y portada están pendientes de revisión.", another: "Enviar otra canción", review: "La canción será revisada antes de entrar en la arena.", rights: "Tengo los derechos para compartir la canción y la portada.", photoSubmit: "Enviar una fotografía", timeLeft: "Tiempo restante", ended: "Duelo terminado", loading: "Cargando duelo…",
  },
  fr: {
    choose: "Choisis ton arène", chooseIntro: "Deux façons de laisser une trace. Par où commencer ?", photography: "Photographique", music: "Musicale", photoDescription: "Deux photographies. Deux regards. Choisis l’image qui te touche.", musicDescription: "Deux artistes. Deux disques. Lance la lecture et laisse parler la musique.", enter: "Entrer dans l’arène", new: "Nouveau", back: "Changer d’arène", competition: "UNSEEN · COMPÉTITION MUSICALE", tagline: "Deux morceaux. Un choix. Le public décide.", demo: "Duel de démonstration", demoNote: "Artistes fictifs et boucles originales de démonstration. Les votes démo ne sont pas enregistrés.", play: "Écouter", pause: "Pause", seek: "Position du morceau", challenger: "Participant", listen: "Clique sur le disque pour écouter", playing: "En lecture", share: "Partager le duel", copied: "Lien copié", shareError: "Impossible de partager le duel.", audioError: "Audio indisponible. Réessaie.", vote: "Voter pour ce morceau", voted: "Vote enregistré", demoVoted: "Préférence démo sélectionnée", voteError: "Impossible d’enregistrer le vote.", submit: "Envoie ton morceau", submitIntro: "Ton son, ta pochette. Ta place dans l’arène.", cover: "Pochette du morceau", coverHint: "JPG, PNG ou WEBP · maximum 5 Mo", audio: "Fichier audio", audioHint: "MP3 ou WAV · maximum 30 Mo", title: "Titre du morceau", artist: "Nom d’artiste", story: "L’histoire du morceau", send: "Envoyer le morceau", sending: "Envoi en cours…", preview: "Ton aperçu", previewHint: "La pochette sera derrière le disque. Ajoute un audio pour l’essayer.", chooseFiles: "Ajoute une pochette et un audio pour continuer.", invalidCover: "Choisis une pochette JPG, PNG ou WEBP de 5 Mo maximum.", invalidAudio: "Choisis un fichier MP3 ou WAV de 30 Mo maximum.", login: "Connecte-toi pour envoyer ton morceau.", unavailable: "Ton aperçu est prêt. Les envois seront disponibles une fois le service musical connecté.", received: "Morceau reçu", receivedDescription: "Ton morceau et ta pochette attendent une validation.", another: "Envoyer un autre morceau", review: "Le morceau sera vérifié avant d’entrer dans l’arène.", rights: "Je possède les droits pour partager le morceau et la pochette.", photoSubmit: "Envoyer une photographie", timeLeft: "Temps restant", ended: "Duel terminé", loading: "Chargement du duel…",
  },
  de: {
    choose: "Wähle deine Arena", chooseIntro: "Zwei Wege, Eindruck zu hinterlassen. Wo fängst du an?", photography: "Fotografie", music: "Musik", photoDescription: "Zwei Fotografien. Zwei Perspektiven. Wähle das Bild, das dich berührt.", musicDescription: "Zwei Künstler. Zwei Platten. Drücke Play und lass die Musik sprechen.", enter: "Arena betreten", new: "Neu", back: "Arena wechseln", competition: "UNSEEN · MUSIKWETTBEWERB", tagline: "Zwei Tracks. Eine Wahl. Das Publikum entscheidet.", demo: "Beispielduell", demoNote: "Fiktive Künstler und eigene Beispiel-Loops. Demo-Stimmen werden nicht gespeichert.", play: "Anhören", pause: "Pause", seek: "Position im Track", challenger: "Teilnehmer", listen: "Klicke auf die Platte zum Anhören", playing: "Wird abgespielt", share: "Duell teilen", copied: "Link kopiert", shareError: "Das Duell konnte nicht geteilt werden.", audioError: "Audio nicht verfügbar. Versuche es erneut.", vote: "Für diesen Track stimmen", voted: "Stimme gespeichert", demoVoted: "Demo-Auswahl getroffen", voteError: "Die Stimme konnte nicht gespeichert werden.", submit: "Track einreichen", submitIntro: "Dein Sound, dein Cover. Dein Platz in der Arena.", cover: "Track-Cover", coverHint: "JPG, PNG oder WEBP · bis 5 MB", audio: "Audiodatei", audioHint: "MP3 oder WAV · bis 30 MB", title: "Track-Titel", artist: "Künstlername", story: "Die Geschichte des Tracks", send: "Track einreichen", sending: "Wird gesendet…", preview: "Deine Vorschau", previewHint: "Dein Cover liegt hinter der Platte. Füge Audio zum Testen hinzu.", chooseFiles: "Füge Cover und Audio hinzu.", invalidCover: "Wähle ein JPG-, PNG- oder WEBP-Cover bis 5 MB.", invalidAudio: "Wähle eine MP3- oder WAV-Datei bis 30 MB.", login: "Melde dich an, um deinen Track einzureichen.", unavailable: "Deine Vorschau ist bereit. Einreichungen sind möglich, sobald der Musikdienst verbunden ist.", received: "Track erhalten", receivedDescription: "Dein Track und Cover warten auf Prüfung.", another: "Weiteren Track einreichen", review: "Der Track wird geprüft, bevor er in die Arena kommt.", rights: "Ich habe die Rechte, diesen Track und das Cover zu teilen.", photoSubmit: "Fotografie einreichen", timeLeft: "Verbleibende Zeit", ended: "Duell beendet", loading: "Duell wird geladen…",
  },
};
